// #Sireum

package RTS.Actuation

import org.sireum._
import RTS._
import RTS.util.Container

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PreState_Container extends Container {
  def api_ports_input: B
  def api_ports_manualActuatorInput: B
}

// container for incoming ports
@datatype class Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PreState_Container_P (
  val api_ports_input: B,
  val api_ports_manualActuatorInput: B) extends Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PreState_Container

// container for incoming ports and state variables
@datatype class Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PreState_Container_PS (
  val api_ports_input: B,
  val api_ports_manualActuatorInput: B) extends Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PreState_Container

@sig trait Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PostState_Container extends Container {
  def api_ports_output: B
}

// container for outgoing ports
@datatype class Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PostState_Container_P (
  val api_ports_output: B) extends Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PostState_Container

// container for outgoing ports and state variables
@datatype class Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PostState_Container_PS (
  val api_ports_output: B) extends Actuator_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_PostState_Container
