#ifndef ACTUATOR_I_ACTUATIONSUBSYSTEM_TEMPPRESSUREACTUATORUNIT_TEMPPRESSUREACTUATOR_ACTUATOR_ADAPTER_H
#define ACTUATOR_I_ACTUATIONSUBSYSTEM_TEMPPRESSUREACTUATORUNIT_TEMPPRESSUREACTUATOR_ACTUATOR_ADAPTER_H

#include <all.h>

Unit RTS_Actuation_Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit RTS_Actuation_Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit RTS_Actuation_Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints RTS_Actuation_Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
