package RTS

import org.sireum._
import art.Art

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Process_Ext {
  def sleep(millis: Z): Unit = halt("stub")

  def time(): Art.Time = halt("stub")
}