#ifndef EVENTCONTROLMOCKTHREAD_I_EVENTCONTROLMOCK_EVENTCONTROLMOCKTHREAD_ADAPTER_H
#define EVENTCONTROLMOCKTHREAD_I_EVENTCONTROLMOCK_EVENTCONTROLMOCKTHREAD_ADAPTER_H

#include <all.h>

Unit RTS_EventControl_EventControlMockThread_i_eventControlMock_eventControlMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit RTS_EventControl_EventControlMockThread_i_eventControlMock_eventControlMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit RTS_EventControl_EventControlMockThread_i_eventControlMock_eventControlMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints RTS_EventControl_EventControlMockThread_i_eventControlMock_eventControlMockThread_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
