// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <sb_InstrumentationMockThread_i.h>
#include <InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter.h>
#include <string.h>
#include <camkes.h>

seqNum_t sb_unit2_saturationLogic_channel4_seqNum;

seqNum_t sb_unit2_saturationLogic_channel3_seqNum;

seqNum_t sb_unit2_saturationLogic_channel2_seqNum;

seqNum_t sb_unit2_saturationLogic_channel1_seqNum;

seqNum_t sb_unit2_pressureLogic_channel4_seqNum;

seqNum_t sb_unit2_pressureLogic_channel3_seqNum;

seqNum_t sb_unit2_pressureLogic_channel2_seqNum;

seqNum_t sb_unit2_pressureLogic_channel1_seqNum;

seqNum_t sb_unit2_temperatureLogic_channel4_seqNum;

seqNum_t sb_unit2_temperatureLogic_channel3_seqNum;

seqNum_t sb_unit2_temperatureLogic_channel2_seqNum;

seqNum_t sb_unit2_temperatureLogic_channel1_seqNum;

seqNum_t sb_unit1_saturationLogic_channel4_seqNum;

seqNum_t sb_unit1_saturationLogic_channel3_seqNum;

seqNum_t sb_unit1_saturationLogic_channel2_seqNum;

seqNum_t sb_unit1_saturationLogic_channel1_seqNum;

seqNum_t sb_unit1_pressureLogic_channel4_seqNum;

seqNum_t sb_unit1_pressureLogic_channel3_seqNum;

seqNum_t sb_unit1_pressureLogic_channel2_seqNum;

seqNum_t sb_unit1_pressureLogic_channel1_seqNum;

seqNum_t sb_unit1_temperatureLogic_channel4_seqNum;

seqNum_t sb_unit1_temperatureLogic_channel3_seqNum;

seqNum_t sb_unit1_temperatureLogic_channel2_seqNum;

seqNum_t sb_unit1_temperatureLogic_channel1_seqNum;

bool sb_unit1_temperatureLogic_channel1_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel1, value, &sb_unit1_temperatureLogic_channel1_seqNum);
}

bool sb_unit1_temperatureLogic_channel2_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel2, value, &sb_unit1_temperatureLogic_channel2_seqNum);
}

bool sb_unit1_temperatureLogic_channel3_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel3, value, &sb_unit1_temperatureLogic_channel3_seqNum);
}

bool sb_unit1_temperatureLogic_channel4_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel4, value, &sb_unit1_temperatureLogic_channel4_seqNum);
}

bool sb_unit1_pressureLogic_channel1_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_pressureLogic_channel1, value, &sb_unit1_pressureLogic_channel1_seqNum);
}

bool sb_unit1_pressureLogic_channel2_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_pressureLogic_channel2, value, &sb_unit1_pressureLogic_channel2_seqNum);
}

bool sb_unit1_pressureLogic_channel3_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_pressureLogic_channel3, value, &sb_unit1_pressureLogic_channel3_seqNum);
}

bool sb_unit1_pressureLogic_channel4_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_pressureLogic_channel4, value, &sb_unit1_pressureLogic_channel4_seqNum);
}

bool sb_unit1_saturationLogic_channel1_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_saturationLogic_channel1, value, &sb_unit1_saturationLogic_channel1_seqNum);
}

bool sb_unit1_saturationLogic_channel2_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_saturationLogic_channel2, value, &sb_unit1_saturationLogic_channel2_seqNum);
}

bool sb_unit1_saturationLogic_channel3_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_saturationLogic_channel3, value, &sb_unit1_saturationLogic_channel3_seqNum);
}

bool sb_unit1_saturationLogic_channel4_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit1_saturationLogic_channel4, value, &sb_unit1_saturationLogic_channel4_seqNum);
}

bool sb_unit2_temperatureLogic_channel1_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel1, value, &sb_unit2_temperatureLogic_channel1_seqNum);
}

bool sb_unit2_temperatureLogic_channel2_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel2, value, &sb_unit2_temperatureLogic_channel2_seqNum);
}

bool sb_unit2_temperatureLogic_channel3_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel3, value, &sb_unit2_temperatureLogic_channel3_seqNum);
}

bool sb_unit2_temperatureLogic_channel4_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel4, value, &sb_unit2_temperatureLogic_channel4_seqNum);
}

bool sb_unit2_pressureLogic_channel1_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_pressureLogic_channel1, value, &sb_unit2_pressureLogic_channel1_seqNum);
}

bool sb_unit2_pressureLogic_channel2_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_pressureLogic_channel2, value, &sb_unit2_pressureLogic_channel2_seqNum);
}

bool sb_unit2_pressureLogic_channel3_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_pressureLogic_channel3, value, &sb_unit2_pressureLogic_channel3_seqNum);
}

bool sb_unit2_pressureLogic_channel4_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_pressureLogic_channel4, value, &sb_unit2_pressureLogic_channel4_seqNum);
}

bool sb_unit2_saturationLogic_channel1_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_saturationLogic_channel1, value, &sb_unit2_saturationLogic_channel1_seqNum);
}

bool sb_unit2_saturationLogic_channel2_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_saturationLogic_channel2, value, &sb_unit2_saturationLogic_channel2_seqNum);
}

bool sb_unit2_saturationLogic_channel3_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_saturationLogic_channel3, value, &sb_unit2_saturationLogic_channel3_seqNum);
}

bool sb_unit2_saturationLogic_channel4_write(const union_art_DataContent * value) {
  return write_sp_union_art_DataContent(sb_unit2_saturationLogic_channel4, value, &sb_unit2_saturationLogic_channel4_seqNum);
}

// send unit1_temperatureLogic_channel1: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel1_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel1_Send", 0);

  sb_unit1_temperatureLogic_channel1_write(d);
}

// send unit1_temperatureLogic_channel2: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel2_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel2_Send", 0);

  sb_unit1_temperatureLogic_channel2_write(d);
}

// send unit1_temperatureLogic_channel3: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel3_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel3_Send", 0);

  sb_unit1_temperatureLogic_channel3_write(d);
}

// send unit1_temperatureLogic_channel4: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel4_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_temperatureLogic_channel4_Send", 0);

  sb_unit1_temperatureLogic_channel4_write(d);
}

// send unit1_pressureLogic_channel1: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel1_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel1_Send", 0);

  sb_unit1_pressureLogic_channel1_write(d);
}

// send unit1_pressureLogic_channel2: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel2_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel2_Send", 0);

  sb_unit1_pressureLogic_channel2_write(d);
}

// send unit1_pressureLogic_channel3: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel3_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel3_Send", 0);

  sb_unit1_pressureLogic_channel3_write(d);
}

// send unit1_pressureLogic_channel4: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel4_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_pressureLogic_channel4_Send", 0);

  sb_unit1_pressureLogic_channel4_write(d);
}

// send unit1_saturationLogic_channel1: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel1_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel1_Send", 0);

  sb_unit1_saturationLogic_channel1_write(d);
}

// send unit1_saturationLogic_channel2: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel2_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel2_Send", 0);

  sb_unit1_saturationLogic_channel2_write(d);
}

// send unit1_saturationLogic_channel3: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel3_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel3_Send", 0);

  sb_unit1_saturationLogic_channel3_write(d);
}

// send unit1_saturationLogic_channel4: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel4_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit1_saturationLogic_channel4_Send", 0);

  sb_unit1_saturationLogic_channel4_write(d);
}

// send unit2_temperatureLogic_channel1: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel1_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel1_Send", 0);

  sb_unit2_temperatureLogic_channel1_write(d);
}

// send unit2_temperatureLogic_channel2: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel2_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel2_Send", 0);

  sb_unit2_temperatureLogic_channel2_write(d);
}

// send unit2_temperatureLogic_channel3: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel3_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel3_Send", 0);

  sb_unit2_temperatureLogic_channel3_write(d);
}

// send unit2_temperatureLogic_channel4: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel4_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_temperatureLogic_channel4_Send", 0);

  sb_unit2_temperatureLogic_channel4_write(d);
}

// send unit2_pressureLogic_channel1: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel1_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel1_Send", 0);

  sb_unit2_pressureLogic_channel1_write(d);
}

// send unit2_pressureLogic_channel2: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel2_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel2_Send", 0);

  sb_unit2_pressureLogic_channel2_write(d);
}

// send unit2_pressureLogic_channel3: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel3_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel3_Send", 0);

  sb_unit2_pressureLogic_channel3_write(d);
}

// send unit2_pressureLogic_channel4: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel4_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_pressureLogic_channel4_Send", 0);

  sb_unit2_pressureLogic_channel4_write(d);
}

// send unit2_saturationLogic_channel1: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel1_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel1_Send", 0);

  sb_unit2_saturationLogic_channel1_write(d);
}

// send unit2_saturationLogic_channel2: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel2_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel2_Send", 0);

  sb_unit2_saturationLogic_channel2_write(d);
}

// send unit2_saturationLogic_channel3: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel3_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel3_Send", 0);

  sb_unit2_saturationLogic_channel3_write(d);
}

// send unit2_saturationLogic_channel4: Out DataPort bool
Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel4_Send(
  STACK_FRAME
  art_DataContent d) {
  DeclNewStackFrame(caller, "sb_InstrumentationMockThread_i.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_seL4Nix_unit2_saturationLogic_channel4_Send", 0);

  sb_unit2_saturationLogic_channel4_write(d);
}

void pre_init(void) {
  DeclNewStackFrame(NULL, "sb_InstrumentationMockThread_i.c", "", "pre_init", 0);

  printf("Entering pre-init of InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread\n");

  // initialise data structure for data port unit1_temperatureLogic_channel1
  init_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel1, &sb_unit1_temperatureLogic_channel1_seqNum);

  // initialise data structure for data port unit1_temperatureLogic_channel2
  init_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel2, &sb_unit1_temperatureLogic_channel2_seqNum);

  // initialise data structure for data port unit1_temperatureLogic_channel3
  init_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel3, &sb_unit1_temperatureLogic_channel3_seqNum);

  // initialise data structure for data port unit1_temperatureLogic_channel4
  init_sp_union_art_DataContent(sb_unit1_temperatureLogic_channel4, &sb_unit1_temperatureLogic_channel4_seqNum);

  // initialise data structure for data port unit1_pressureLogic_channel1
  init_sp_union_art_DataContent(sb_unit1_pressureLogic_channel1, &sb_unit1_pressureLogic_channel1_seqNum);

  // initialise data structure for data port unit1_pressureLogic_channel2
  init_sp_union_art_DataContent(sb_unit1_pressureLogic_channel2, &sb_unit1_pressureLogic_channel2_seqNum);

  // initialise data structure for data port unit1_pressureLogic_channel3
  init_sp_union_art_DataContent(sb_unit1_pressureLogic_channel3, &sb_unit1_pressureLogic_channel3_seqNum);

  // initialise data structure for data port unit1_pressureLogic_channel4
  init_sp_union_art_DataContent(sb_unit1_pressureLogic_channel4, &sb_unit1_pressureLogic_channel4_seqNum);

  // initialise data structure for data port unit1_saturationLogic_channel1
  init_sp_union_art_DataContent(sb_unit1_saturationLogic_channel1, &sb_unit1_saturationLogic_channel1_seqNum);

  // initialise data structure for data port unit1_saturationLogic_channel2
  init_sp_union_art_DataContent(sb_unit1_saturationLogic_channel2, &sb_unit1_saturationLogic_channel2_seqNum);

  // initialise data structure for data port unit1_saturationLogic_channel3
  init_sp_union_art_DataContent(sb_unit1_saturationLogic_channel3, &sb_unit1_saturationLogic_channel3_seqNum);

  // initialise data structure for data port unit1_saturationLogic_channel4
  init_sp_union_art_DataContent(sb_unit1_saturationLogic_channel4, &sb_unit1_saturationLogic_channel4_seqNum);

  // initialise data structure for data port unit2_temperatureLogic_channel1
  init_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel1, &sb_unit2_temperatureLogic_channel1_seqNum);

  // initialise data structure for data port unit2_temperatureLogic_channel2
  init_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel2, &sb_unit2_temperatureLogic_channel2_seqNum);

  // initialise data structure for data port unit2_temperatureLogic_channel3
  init_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel3, &sb_unit2_temperatureLogic_channel3_seqNum);

  // initialise data structure for data port unit2_temperatureLogic_channel4
  init_sp_union_art_DataContent(sb_unit2_temperatureLogic_channel4, &sb_unit2_temperatureLogic_channel4_seqNum);

  // initialise data structure for data port unit2_pressureLogic_channel1
  init_sp_union_art_DataContent(sb_unit2_pressureLogic_channel1, &sb_unit2_pressureLogic_channel1_seqNum);

  // initialise data structure for data port unit2_pressureLogic_channel2
  init_sp_union_art_DataContent(sb_unit2_pressureLogic_channel2, &sb_unit2_pressureLogic_channel2_seqNum);

  // initialise data structure for data port unit2_pressureLogic_channel3
  init_sp_union_art_DataContent(sb_unit2_pressureLogic_channel3, &sb_unit2_pressureLogic_channel3_seqNum);

  // initialise data structure for data port unit2_pressureLogic_channel4
  init_sp_union_art_DataContent(sb_unit2_pressureLogic_channel4, &sb_unit2_pressureLogic_channel4_seqNum);

  // initialise data structure for data port unit2_saturationLogic_channel1
  init_sp_union_art_DataContent(sb_unit2_saturationLogic_channel1, &sb_unit2_saturationLogic_channel1_seqNum);

  // initialise data structure for data port unit2_saturationLogic_channel2
  init_sp_union_art_DataContent(sb_unit2_saturationLogic_channel2, &sb_unit2_saturationLogic_channel2_seqNum);

  // initialise data structure for data port unit2_saturationLogic_channel3
  init_sp_union_art_DataContent(sb_unit2_saturationLogic_channel3, &sb_unit2_saturationLogic_channel3_seqNum);

  // initialise data structure for data port unit2_saturationLogic_channel4
  init_sp_union_art_DataContent(sb_unit2_saturationLogic_channel4, &sb_unit2_saturationLogic_channel4_seqNum);

  // initialise slang-embedded components/ports
  RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseArchitecture(SF_LAST);

  // call the component's initialise entrypoint
  RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseEntryPoint(SF_LAST);

  printf("Leaving pre-init of InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread\n");
}

/************************************************************************
 * int run(void)
 * Main active thread function.
 ************************************************************************/
int run(void) {
  DeclNewStackFrame(NULL, "sb_InstrumentationMockThread_i.c", "", "run", 0);

  sb_self_pacer_tick_emit();
  for(;;) {
    sb_self_pacer_tock_wait();
    // call the component's compute entrypoint
    RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_computeEntryPoint(SF_LAST);
    sb_self_pacer_tick_emit();
  }
  return 0;
}
