#ifndef COINCIDENCELOGIC_I_ACTUATIONSUBSYSTEM_ACTUATIONUNIT1_SATURATIONLOGIC_COINCIDENCELOGIC_ADAPTER_H
#define COINCIDENCELOGIC_I_ACTUATIONSUBSYSTEM_ACTUATIONUNIT1_SATURATIONLOGIC_COINCIDENCELOGIC_ADAPTER_H

#include <all.h>

Unit RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_saturationLogic_coincidenceLogic_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_saturationLogic_coincidenceLogic_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_saturationLogic_coincidenceLogic_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_saturationLogic_coincidenceLogic_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
