#include <OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter.h>

Unit RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter.c", "", "RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_initialiseArchitecture", 0);

  RTS_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_orLogic_initialiseArchitecture(SF_LAST);
}

Unit RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter.c", "", "RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_initialiseEntryPoint", 0);

  RTS_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_orLogic_initialiseEntryPoint(SF_LAST);
}

Unit RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter.c", "", "RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_computeEntryPoint", 0);

  RTS_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_orLogic_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter.c", "", "RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_entryPoints", 0);

  return RTS_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_orLogic_entryPoints(SF_LAST);
}
