#ifndef ORLOGIC_I_ACTUATIONSUBSYSTEM_ACTUATIONUNIT2_TEMPPRESSURETRIPOUT_ORLOGIC_ADAPTER_H
#define ORLOGIC_I_ACTUATIONSUBSYSTEM_ACTUATIONUNIT2_TEMPPRESSURETRIPOUT_ORLOGIC_ADAPTER_H

#include <all.h>

Unit RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
