#include <InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter.h>

Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseArchitecture", 0);

  RTS_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_instrumentationMockThread_seL4App_initialiseArchitecture(SF_LAST);
}

Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseEntryPoint", 0);

  RTS_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_instrumentationMockThread_seL4App_initialiseEntryPoint(SF_LAST);
}

Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_computeEntryPoint", 0);

  RTS_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_instrumentationMockThread_seL4App_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter.c", "", "RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_entryPoints", 0);

  return RTS_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_instrumentationMockThread_seL4App_entryPoints(SF_LAST);
}
