#ifndef INSTRUMENTATIONMOCKTHREAD_I_INSTRUMENTATIONMOCK_INSTRUMENTATIONMOCKTHREAD_ADAPTER_H
#define INSTRUMENTATIONMOCKTHREAD_I_INSTRUMENTATIONMOCK_INSTRUMENTATIONMOCKTHREAD_ADAPTER_H

#include <all.h>

Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
