#ifndef ACTUATORSMOCKTHREAD_I_ACTUATORSMOCK_ACTUATORSMOCKTHREAD_ADAPTER_H
#define ACTUATORSMOCKTHREAD_I_ACTUATORSMOCK_ACTUATORSMOCKTHREAD_ADAPTER_H

#include <all.h>

Unit RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
