#include <ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter.h>

Unit RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter.c", "", "RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_initialiseArchitecture", 0);

  RTS_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_actuatorsMockThread_initialiseArchitecture(SF_LAST);
}

Unit RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter.c", "", "RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_initialiseEntryPoint", 0);

  RTS_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_actuatorsMockThread_initialiseEntryPoint(SF_LAST);
}

Unit RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter.c", "", "RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_computeEntryPoint", 0);

  RTS_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_actuatorsMockThread_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter.c", "", "RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_adapter_entryPoints", 0);

  return RTS_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_actuatorsMockThread_entryPoints(SF_LAST);
}
