// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_ACTUATORSMOCKTHREAD_I_H
#define SB_ACTUATORSMOCKTHREAD_I_H

#include <sb_types.h>

bool sb_tempPressureActuate_read(union_art_DataContent * value);

bool sb_saturationActuate_read(union_art_DataContent * value);

#endif // SB_ACTUATORSMOCKTHREAD_I_H
