package RTS.EventControl

import org.sireum._
import art._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object EventControlMockThread_i_eventControlMock_eventControlMockThread_seL4Nix_Ext {
  def manualActuatorInput1_Send(d: DataContent): Unit = halt("stub")

  def manualActuatorInput2_Send(d: DataContent): Unit = halt("stub")
}
