// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_INSTRUMENTATIONMOCKTHREAD_I_H
#define SB_INSTRUMENTATIONMOCKTHREAD_I_H

#include <sb_types.h>

bool sb_unit1_temperatureLogic_channel1_write(const union_art_DataContent * value);

bool sb_unit1_temperatureLogic_channel2_write(const union_art_DataContent * value);

bool sb_unit1_temperatureLogic_channel3_write(const union_art_DataContent * value);

bool sb_unit1_temperatureLogic_channel4_write(const union_art_DataContent * value);

bool sb_unit1_pressureLogic_channel1_write(const union_art_DataContent * value);

bool sb_unit1_pressureLogic_channel2_write(const union_art_DataContent * value);

bool sb_unit1_pressureLogic_channel3_write(const union_art_DataContent * value);

bool sb_unit1_pressureLogic_channel4_write(const union_art_DataContent * value);

bool sb_unit1_saturationLogic_channel1_write(const union_art_DataContent * value);

bool sb_unit1_saturationLogic_channel2_write(const union_art_DataContent * value);

bool sb_unit1_saturationLogic_channel3_write(const union_art_DataContent * value);

bool sb_unit1_saturationLogic_channel4_write(const union_art_DataContent * value);

bool sb_unit2_temperatureLogic_channel1_write(const union_art_DataContent * value);

bool sb_unit2_temperatureLogic_channel2_write(const union_art_DataContent * value);

bool sb_unit2_temperatureLogic_channel3_write(const union_art_DataContent * value);

bool sb_unit2_temperatureLogic_channel4_write(const union_art_DataContent * value);

bool sb_unit2_pressureLogic_channel1_write(const union_art_DataContent * value);

bool sb_unit2_pressureLogic_channel2_write(const union_art_DataContent * value);

bool sb_unit2_pressureLogic_channel3_write(const union_art_DataContent * value);

bool sb_unit2_pressureLogic_channel4_write(const union_art_DataContent * value);

bool sb_unit2_saturationLogic_channel1_write(const union_art_DataContent * value);

bool sb_unit2_saturationLogic_channel2_write(const union_art_DataContent * value);

bool sb_unit2_saturationLogic_channel3_write(const union_art_DataContent * value);

bool sb_unit2_saturationLogic_channel4_write(const union_art_DataContent * value);

#endif // SB_INSTRUMENTATIONMOCKTHREAD_I_H
