#ifndef SIREUM_GEN_H
#define SIREUM_GEN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <misc.h>
#include <type-RTS_Actuation_Actuator_i_Api.h>
#include <type-RTS_Actuation_Actuator_i_Initialization_Api.h>
#include <type-RTS_Actuation_Actuator_i_Operational_Api.h>
#include <type-RTS_Actuation_Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator.h>
#include <type-RTS_Actuation_Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator_Bridge.h>
#include <type-RTS_Actuation_Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator.h>
#include <type-RTS_Actuation_Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_Bridge.h>
#include <type-RTS_Actuation_Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_Api.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_Initialization_Api.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_Operational_Api.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_Bridge.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_pressureLogic_coincidenceLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_saturationLogic_coincidenceLogic.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_saturationLogic_coincidenceLogic_Bridge.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_saturationLogic_coincidenceLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_temperatureLogic_coincidenceLogic.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_temperatureLogic_coincidenceLogic_Bridge.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit1_temperatureLogic_coincidenceLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_pressureLogic_coincidenceLogic.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_pressureLogic_coincidenceLogic_Bridge.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_pressureLogic_coincidenceLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_saturationLogic_coincidenceLogic.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_saturationLogic_coincidenceLogic_Bridge.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_saturationLogic_coincidenceLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_temperatureLogic_coincidenceLogic.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_temperatureLogic_coincidenceLogic_Bridge.h>
#include <type-RTS_Actuation_CoincidenceLogic_i_actuationSubsystem_actuationUnit2_temperatureLogic_coincidenceLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_OrLogic_i_Api.h>
#include <type-RTS_Actuation_OrLogic_i_Initialization_Api.h>
#include <type-RTS_Actuation_OrLogic_i_Operational_Api.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit1_tempPressureTripOut_orLogic.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit1_tempPressureTripOut_orLogic_Bridge.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit1_tempPressureTripOut_orLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_Bridge.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_saturationActuatorUnit_actuateSaturationActuator_orLogic.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_saturationActuatorUnit_actuateSaturationActuator_orLogic_Bridge.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_saturationActuatorUnit_actuateSaturationActuator_orLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_tempPressureActuatorUnit_actuateTempPressureActuator_orLogic.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_tempPressureActuatorUnit_actuateTempPressureActuator_orLogic_Bridge.h>
#include <type-RTS_Actuation_OrLogic_i_actuationSubsystem_tempPressureActuatorUnit_actuateTempPressureActuator_orLogic_Bridge_EntryPoints.h>
#include <type-RTS_Actuators_ActuatorsMockThread_i_Api.h>
#include <type-RTS_Actuators_ActuatorsMockThread_i_Initialization_Api.h>
#include <type-RTS_Actuators_ActuatorsMockThread_i_Operational_Api.h>
#include <type-RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread.h>
#include <type-RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_Bridge.h>
#include <type-RTS_Actuators_ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_Bridge_EntryPoints.h>
#include <type-RTS_Arch.h>
#include <type-RTS_Base_Types.h>
#include <type-RTS_Base_Types_Boolean_Payload.h>
#include <type-RTS_Base_Types_Character_Payload.h>
#include <type-RTS_Base_Types_Float_32_Payload.h>
#include <type-RTS_Base_Types_Float_64_Payload.h>
#include <type-RTS_Base_Types_Float_Payload.h>
#include <type-RTS_Base_Types_Integer_16_Payload.h>
#include <type-RTS_Base_Types_Integer_32_Payload.h>
#include <type-RTS_Base_Types_Integer_64_Payload.h>
#include <type-RTS_Base_Types_Integer_8_Payload.h>
#include <type-RTS_Base_Types_Integer_Payload.h>
#include <type-RTS_Base_Types_String_Payload.h>
#include <type-RTS_Base_Types_Unsigned_16_Payload.h>
#include <type-RTS_Base_Types_Unsigned_32_Payload.h>
#include <type-RTS_Base_Types_Unsigned_64_Payload.h>
#include <type-RTS_Base_Types_Unsigned_8_Payload.h>
#include <type-RTS_Cli.h>
#include <type-RTS_Cli_HelpOption.h>
#include <type-RTS_Cli_RunChoice_Type.h>
#include <type-RTS_Cli_RunOption.h>
#include <type-RTS_Cli_RunTopOption.h>
#include <type-RTS_Demo.h>
#include <type-RTS_EventControl_EventControlMockThread_i_Api.h>
#include <type-RTS_EventControl_EventControlMockThread_i_Initialization_Api.h>
#include <type-RTS_EventControl_EventControlMockThread_i_Operational_Api.h>
#include <type-RTS_EventControl_EventControlMockThread_i_eventControlMock_eventControlMockThread.h>
#include <type-RTS_EventControl_EventControlMockThread_i_eventControlMock_eventControlMockThread_Bridge.h>
#include <type-RTS_EventControl_EventControlMockThread_i_eventControlMock_eventControlMockThread_Bridge_EntryPoints.h>
#include <type-RTS_Instrumentation_InstrumentationMockThread_i_Api.h>
#include <type-RTS_Instrumentation_InstrumentationMockThread_i_Initialization_Api.h>
#include <type-RTS_Instrumentation_InstrumentationMockThread_i_Operational_Api.h>
#include <type-RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread.h>
#include <type-RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_Bridge.h>
#include <type-RTS_Instrumentation_InstrumentationMockThread_i_instrumentationMock_instrumentationMockThread_Bridge_EntryPoints.h>
#include <type-RTS_Platform.h>
#include <type-RTS_ProcessorTimingProperties.h>
#include <type-RTS_ScheduleProviderI.h>
#include <type-RTS_Schedulers.h>
#include <type-RTS_ThreadTimingProperties.h>
#include <type-RTS_TranspilerToucher.h>
#include <type-RTS_TranspilerUtil.h>
#include <type-art_ArchitectureDescription.h>
#include <type-art_Art.h>
#include <type-art_Art_BridgeId.h>
#include <type-art_Art_ConnectionId.h>
#include <type-art_ArtNativeSlang.h>
#include <type-art_Art_PortId.h>
#include <type-art_ArtSlangMessage.h>
#include <type-art_Bridge.h>
#include <type-art_Bridge_EntryPoints.h>
#include <type-art_Bridge_Ports.h>
#include <type-art_Connection.h>
#include <type-art_DataContent.h>
#include <type-art_DispatchPropertyProtocol.h>
#include <type-art_DispatchPropertyProtocol_Periodic.h>
#include <type-art_DispatchPropertyProtocol_Sporadic.h>
#include <type-art_Empty.h>
#include <type-art_PortMode_Type.h>
#include <type-art_Process.h>
#include <type-art_UConnection.h>
#include <type-art_UPort.h>
#include <type-art_art_Port_C0524D.h>
#include <type-art_scheduling_Scheduler.h>
#include <type-art_scheduling_legacy_Legacy.h>
#include <type-art_scheduling_legacy_LegacyInterface.h>
#include <type-art_scheduling_roundrobin_RoundRobin.h>
#include <type-art_scheduling_roundrobin_RoundRobinExtensions.h>
#include <type-art_scheduling_static_CliInfoProvider.h>
#include <type-art_scheduling_static_Command.h>
#include <type-art_scheduling_static_CommandInterpreter.h>
#include <type-art_scheduling_static_CommandProvider.h>
#include <type-art_scheduling_static_DefaultCommandProvider.h>
#include <type-art_scheduling_static_Explorer.h>
#include <type-art_scheduling_static_Explorer_ScheduleState.h>
#include <type-art_scheduling_static_Help.h>
#include <type-art_scheduling_static_Hstep.h>
#include <type-art_scheduling_static_InfoCommandProvider.h>
#include <type-art_scheduling_static_InfoComponentState.h>
#include <type-art_scheduling_static_InfoComponentStateId.h>
#include <type-art_scheduling_static_InfoInputs.h>
#include <type-art_scheduling_static_InfoOutputs.h>
#include <type-art_scheduling_static_InfoThreadNickNames.h>
#include <type-art_scheduling_static_Infoschedule.h>
#include <type-art_scheduling_static_Infostate.h>
#include <type-art_scheduling_static_RunToDomain.h>
#include <type-art_scheduling_static_RunToHP.h>
#include <type-art_scheduling_static_RunToSlot.h>
#include <type-art_scheduling_static_RunToState.h>
#include <type-art_scheduling_static_RunToThread.h>
#include <type-art_scheduling_static_Schedule.h>
#include <type-art_scheduling_static_Schedule_DSchedule.h>
#include <type-art_scheduling_static_Schedule_DScheduleSpec.h>
#include <type-art_scheduling_static_Schedule_Slot.h>
#include <type-art_scheduling_static_Sstep.h>
#include <type-art_scheduling_static_StateObserver.h>
#include <type-art_scheduling_static_StaticScheduler.h>
#include <type-art_scheduling_static_StaticSchedulerIO.h>
#include <type-art_scheduling_static_Stop.h>
#include <type-art_scheduling_static_Unrecognized.h>
#include <type-art_scheduling_static_Unsupported.h>
#include <type-org_sireum_AssocS_Entries.h>
#include <type-org_sireum_IS_058E6F.h>
#include <type-org_sireum_IS_0C7B5E.h>
#include <type-org_sireum_IS_39643F.h>
#include <type-org_sireum_IS_4D6DA5.h>
#include <type-org_sireum_IS_588B23.h>
#include <type-org_sireum_IS_5AA467.h>
#include <type-org_sireum_IS_7267A0.h>
#include <type-org_sireum_IS_7DA5C1.h>
#include <type-org_sireum_IS_820232.h>
#include <type-org_sireum_IS_948B60.h>
#include <type-org_sireum_IS_996770.h>
#include <type-org_sireum_IS_D10119.h>
#include <type-org_sireum_IS_FDDCB6.h>
#include <type-org_sireum_MBox2_37E193.h>
#include <type-org_sireum_MBox2_43CC67.h>
#include <type-org_sireum_MNone_6579ED.h>
#include <type-org_sireum_MOption_AEC260.h>
#include <type-org_sireum_MS_83D5EB.h>
#include <type-org_sireum_MS_9C0286.h>
#include <type-org_sireum_MS_A7EF1B.h>
#include <type-org_sireum_MS_CA6EDB.h>
#include <type-org_sireum_MSome_30C95B.h>
#include <type-org_sireum_Map.h>
#include <type-org_sireum_Map_9C6840.h>
#include <type-org_sireum_Map_EB5A91.h>
#include <type-org_sireum_None.h>
#include <type-org_sireum_None_00347F.h>
#include <type-org_sireum_None_080F67.h>
#include <type-org_sireum_None_174952.h>
#include <type-org_sireum_None_1A60DD.h>
#include <type-org_sireum_None_1AA45D.h>
#include <type-org_sireum_None_1FE67C.h>
#include <type-org_sireum_None_2939E3.h>
#include <type-org_sireum_None_336F0A.h>
#include <type-org_sireum_None_37A019.h>
#include <type-org_sireum_None_39BC5F.h>
#include <type-org_sireum_None_50AF88.h>
#include <type-org_sireum_None_52D9AF.h>
#include <type-org_sireum_None_5F3A7A.h>
#include <type-org_sireum_None_734370.h>
#include <type-org_sireum_None_76463B.h>
#include <type-org_sireum_None_7E20F8.h>
#include <type-org_sireum_None_8BED90.h>
#include <type-org_sireum_None_8D6171.h>
#include <type-org_sireum_None_8D8A06.h>
#include <type-org_sireum_None_964667.h>
#include <type-org_sireum_None_9803C0.h>
#include <type-org_sireum_None_B2694B.h>
#include <type-org_sireum_None_C050C2.h>
#include <type-org_sireum_None_CFD2B0.h>
#include <type-org_sireum_None_D34309.h>
#include <type-org_sireum_Nothing.h>
#include <type-org_sireum_Option_0247A1.h>
#include <type-org_sireum_Option_069397.h>
#include <type-org_sireum_Option_06B15F.h>
#include <type-org_sireum_Option_0E107D.h>
#include <type-org_sireum_Option_1C3ADA.h>
#include <type-org_sireum_Option_1CF021.h>
#include <type-org_sireum_Option_376396.h>
#include <type-org_sireum_Option_4ACA0C.h>
#include <type-org_sireum_Option_549EB3.h>
#include <type-org_sireum_Option_5BBD7F.h>
#include <type-org_sireum_Option_5CC377.h>
#include <type-org_sireum_Option_6239DB.h>
#include <type-org_sireum_Option_638957.h>
#include <type-org_sireum_Option_73E809.h>
#include <type-org_sireum_Option_7BBFBE.h>
#include <type-org_sireum_Option_80DE21.h>
#include <type-org_sireum_Option_882048.h>
#include <type-org_sireum_Option_8E9F45.h>
#include <type-org_sireum_Option_8F4D4C.h>
#include <type-org_sireum_Option_A836EB.h>
#include <type-org_sireum_Option_B47750.h>
#include <type-org_sireum_Option_BF489E.h>
#include <type-org_sireum_Option_DB2CFC.h>
#include <type-org_sireum_Option_E142FF.h>
#include <type-org_sireum_Option_E8BC07.h>
#include <type-org_sireum_Option_FEE1DB.h>
#include <type-org_sireum_S16.h>
#include <type-org_sireum_S32.h>
#include <type-org_sireum_S64.h>
#include <type-org_sireum_S8.h>
#include <type-org_sireum_Some.h>
#include <type-org_sireum_Some_24B656.h>
#include <type-org_sireum_Some_2BC073.h>
#include <type-org_sireum_Some_3E197E.h>
#include <type-org_sireum_Some_42319A.h>
#include <type-org_sireum_Some_4347C6.h>
#include <type-org_sireum_Some_482E57.h>
#include <type-org_sireum_Some_488F47.h>
#include <type-org_sireum_Some_51E221.h>
#include <type-org_sireum_Some_6D5259.h>
#include <type-org_sireum_Some_6FC748.h>
#include <type-org_sireum_Some_7A7168.h>
#include <type-org_sireum_Some_7FC307.h>
#include <type-org_sireum_Some_80A548.h>
#include <type-org_sireum_Some_824C23.h>
#include <type-org_sireum_Some_9D1CD4.h>
#include <type-org_sireum_Some_A0133F.h>
#include <type-org_sireum_Some_B05425.h>
#include <type-org_sireum_Some_B8733D.h>
#include <type-org_sireum_Some_B8A5BD.h>
#include <type-org_sireum_Some_B99BC9.h>
#include <type-org_sireum_Some_C4F557.h>
#include <type-org_sireum_Some_D29615.h>
#include <type-org_sireum_Some_DB59FB.h>
#include <type-org_sireum_Some_E625E9.h>
#include <type-org_sireum_Some_E8C0F3.h>
#include <type-org_sireum_Tuple12_3FBE62.h>
#include <type-org_sireum_Tuple2_04A4F6.h>
#include <type-org_sireum_Tuple2_0862A0.h>
#include <type-org_sireum_Tuple2_275908.h>
#include <type-org_sireum_Tuple2_4DFC06.h>
#include <type-org_sireum_Tuple2_A29DBA.h>
#include <type-org_sireum_Tuple2_E0098E.h>
#include <type-org_sireum_Tuple2_EC3B57.h>
#include <type-org_sireum_Tuple4_FA9F23.h>
#include <type-org_sireum_U16.h>
#include <type-org_sireum_U32.h>
#include <type-org_sireum_U64.h>
#include <type-org_sireum_U8.h>
#include <type-org_sireum_conversions_Z.h>

#if defined(static_assert)
#define STATIC_ASSERT static_assert
#define GLOBAL_STATIC_ASSERT(a, b, c) static_assert(b, c)
#else
#define STATIC_ASSERT(pred, explanation); {char assert=1/(pred);(void)assert;}
#define GLOBAL_STATIC_ASSERT(unique, pred, explanation); namespace ASSERTION {char unique=1/(pred);}
#endif

size_t sizeOf(Type t);
void Type_assign(void *dest, void *src, size_t destSize);

#ifdef __cplusplus
}
#endif

#endif