// #Sireum
package RTS.Actuators

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@msig trait ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_Injection_Provider {
  def pre_receiveInput(): Unit
}

object ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_Injection_Service {

  var providers: MSZ[ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_Injection_Provider] = MSZ()

  def register(provider: ActuatorsMockThread_i_actuatorsMock_actuatorsMockThread_Injection_Provider): Unit = {
    providers = providers :+ provider
  }

  def pre_receiveInput(): Unit = {
    for (provider <- providers) {
      provider.pre_receiveInput()
    }
  }
}