// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_ACTUATOR_I_H
#define SB_ACTUATOR_I_H

#include <sb_types.h>

bool sb_input_read(union_art_DataContent * value);

bool sb_manualActuatorInput_read(union_art_DataContent * value);

bool sb_output_write(const union_art_DataContent * value);

#endif // SB_ACTUATOR_I_H
